@startuml
title PUP Processing Flow
entity platform.upload.advisor
entity platform.upload.validation
participant pup
entity platform.systemprofile
participant hbi
platform.upload.advisor->pup: msg
Note right of platform.upload.advisor: {"request_id": "abcd1234",\n"account": "000001",\n"principal": "123456",\n"id": "inventoryID if available",\n"size": "size_in_bytes",\n"service": "destination service",\n"category": "file category",\n"url": "bucket_url",\n"b64_identity": "base64_identity_string",\n"metadata": {}\n}
pup->pup: Downloads archive from\nS3 bucket
pup->pup: Extracts facts from archive\nwith insights-core
alt success
    alt if inventory ID not in msg
        pup->hbi: Post to inventory via HTTP
        Note right of pup: Post Data: [{"facts": {"facts": {}}]
        hbi->pup: Response from HBI
        Note left of hbi: Response: {"total": 1,\n"errors": 0,\n"data": [{"status": 0,\n"host": <host_json with facts, insights_id, id, etc.>}]}
        Note left of hbi: See HBI api.spec for more details
    end
    pup->platform.systemprofile: Send system profile to inventory via MQ
    Note right of pup: {"id": "inventory_id",\n"account": "000001",\n"request_id": "abcd1234",\n"system_profile": {}}
else failure
    pup[#0000FF]->platform.upload.validation: msg
    Note left of pup: {"request_id": "abcd1234",\n"validation": "failure"}
end
platform.systemprofile->hbi: msg
@enduml